grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      n_estimators:
      - 200
      - 300
  module_2:
    class: XGBRegressor
    module: xgboost
    params:
      eta: 0.2
    search_param_grid:
      max_depth:
      - 5
      - 10
  module_3:
    class: CatBoostRegressor
    module: catboost
    params:
      learning_rate: 0.1
    search_param_grid:
      depth:
      - 6
      - 8
  module_4:
    class: LGBMRegressor
    module: lightgbm
    params:
      learning_rate: 0.2
    search_param_grid:
      n_estimators:
      - 100
      - 200
      - 300